### ISSUE TITLE
Is it possible to feed a list of text prompts? 

### ISSUE THREAD

**Issue by GeorgePearse** [IDEA-Research/GroundingDINO#10]
When I've tried to feed a list of text prompts to the model, I've only received predictions for the last string. 

Is this user error or how the API is currently designed?

**Comment by SlongLiu** [comment]
Our demo `demo/inference_on_a_image.py` is designed as an example for single image processes. The user needs to modify codes for a list of text prompts. For example, you can duplicate the input image to orginize a batch for multiple texts.
