### ISSUE TITLE
Running it with a very long text prompt (or large number of classes)

### ISSUE THREAD

**Issue by rohit901** [IDEA-Research/GroundingDINO#129]
Hello, I'm trying to run the object detection workflow using Grounding Dino SwinB model (`groundingdino_swinb_cogcoor`)
and I'm having 1000+ classes in my dataset (LVIS). When passing the text prompt and image to the model for forward pass, I'm getting this output:

> Token indices sequence length is longer than the specified maximum sequence length for this model (4283 > 512). Running this sequence through the model will result in indexing errors

Does it mean that the inference will not be working properly when we have LVIS classes? Is there any workaround for it so that I'm still able to use all the classes in the text prompts and get results on LVIS?

**Comment by rentainhe** [comment]
> Hello, I'm trying to run the object detection workflow using Grounding Dino SwinB model (`groundingdino_swinb_cogcoor`) and I'm having 1000+ classes in my dataset (LVIS). When passing the text prompt and image to the model for forward pass, I'm getting this output:
> 
> > Token indices sequence length is longer than the specified maximum sequence length for this model (4283 > 512). Running this sequence through the model will result in indexing errors
> 
> Does it mean that the inference will not be working properly when we have LVIS classes? Is there any workaround for it so that I'm still able to use all the classes in the text prompts and get results on LVIS?

GroundingDINO did not support such a long text prompt for inference, you can split LVIS classes into different parts and running more than one forward pass

**Comment by rohit901** [comment]
Ahh I see, thank you for the confirmation. I was also planning on doing just that... splitting the LVIS classes so that it fits into the text prompt and then running multiple forward passes covering all the classes...

I would be closing this issue since you have made it clear.

**Comment by danigarciaoca** [comment]
Hi! Sorry, just to confirm if I have understood it properly:
- the maximum number of tokens to use in the input text sequence is [256] ([max_text_len](https://github.com/IDEA-Research/GroundingDINO/blob/main/groundingdino/config/GroundingDINO_SwinT_OGC.py#L33))
- the maximum number of objects that can be detected in a single image are 900 ([num_query](https://github.com/IDEA-Research/GroundingDINO/blob/main/groundingdino/config/GroundingDINO_SwinT_OGC.py#L16))

am I right?

Thanks in advance!

**Comment by rohit901** [comment]
Hi Daniel,

I believe you are correct. Thus we would need to split the class text prompt if it becomes too large. I'm splitting the classes by length of 81 each time, and using the zero-shot evaluation code uploaded by the authors @rentainhe @SlongLiu, and modified it for evaluating on LVIS.

Thanks,

**Comment by danigarciaoca** [comment]
Thanks @rohit901!

**Comment by rishabh-akridata** [comment]
@rohit901 If you don't mind can you please share your evaluation code for this?

**Comment by rohit901** [comment]
Sure, you can find it in my recent project's repo:https://github.com/rohit901/cooperative-foundational-models

could you please star the repo and spread the word about it, it would mean a lot!
