### ISSUE TITLE
How can I use specified image to image editing

### ISSUE THREAD

**Issue by yinjiahuidada** [IDEA-Research/GroundingDINO#130]
I find the project can edit image by useing image_inpainting， but I would like to know when I get the image mask，can I use  specified image to inpaint it.

Or it will be a recommendation

**Comment by rentainhe** [comment]
> I find the project can edit image by useing image_inpainting， but I would like to know when I get the image mask，can I use specified image to inpaint it.
> 
> Or it will be a recommendation

Maybe you can try to use [Grounded-SAM](https://github.com/IDEA-Research/Grounded-Segment-Anything#skier-grounded-sam-with-inpainting-detect-segment-and-generate-everything-with-text-prompt) for this function

**Comment by yinjiahuidada** [comment]
> > I find the project can edit image by useing image_inpainting， but I would like to know when I get the image mask，can I use specified image to inpaint it.
> > Or it will be a recommendation
> 
> Maybe you can try to use [Grounded-SAM](https://github.com/IDEA-Research/Grounded-Segment-Anything#skier-grounded-sam-with-inpainting-detect-segment-and-generate-everything-with-text-prompt) which is based on GroundingDINO for this application, you can also find such application in GroundingDINO repo here: https://github.com/IDEA-Research/GroundingDINO/blob/main/demo/image_editing_with_groundingdino_gligen.ipynb

I got this demo.  The following code in GroundingDINO  shows how to change a certain mask.

```
prompt = "'a cat', 'a rose'"
num_box = len(boxes)
image_inpainting = pipe(
    prompt,
    num_images_per_prompt = 2,
    gligen_phrases = gligen_phrases,
    gligen_inpaint_image = image_source_for_inpaint,
    gligen_boxes = xyxy_boxes,
    gligen_scheduled_sampling_beta=1,
    output_type="numpy",
    num_inference_steps=50
).images
```

My question is that if i can change this cat by my own image that had already exist in my system, path will like '/home/root/images/cat.jpg'

**Comment by yinjiahuidada** [comment]
got it, thanks
