### ISSUE TITLE
How to optimise via IoU if too many similar objects are detected?

### ISSUE THREAD

**Issue by XinyueZ** [IDEA-Research/GroundingDINO#131]
Hey, I always have a very large bbox when I query text-prompt "a house" , meanwhile single ones are detected correctly.
How to avoid the large bbox, at least I want to get an approach generally to filter the large ones.

thanks

![000000011](https://github.com/IDEA-Research/GroundingDINO/assets/7869833/a6db11f0-21fe-47a0-96dd-1bec27ea4dd9)

**Comment by rentainhe** [comment]
You can add NMS after the output box

**Comment by XinyueZ** [comment]
@rentainhe Does this repo provide an implementation of it?

**Comment by rentainhe** [comment]
> @rentainhe Does this repo provide an implementation of it?

Please refer to here: https://github.com/IDEA-Research/Grounded-Segment-Anything/blob/8124fe737dc877ec49a0881785119fe222a4c868/automatic_label_simple_demo.py#L104

**Comment by XinyueZ** [comment]
yeah, thank you I  have seen it
