### ISSUE TITLE
关于在coco上finetune训练的问题 (有的情况下finetune时会突然掉点，以及 still 0.4map gap on 2017val)

### ISSUE THREAD

**Issue by drilistbox** [IDEA-Research/GroundingDINO#166]
![image](https://github.com/IDEA-Research/GroundingDINO/assets/14495189/e070e6f0-3156-432a-8902-6ba37dbd1bcb)
作者您好，下面所有的描述都是以上图中红框的设置进行实验的。
我在复现groundingding的训练代码，用作者开源的swin-t在O365,GoldG,Cap4M上预训练模型，直接在coco val2017上评估，性能是48.4map。
然后在coco上的finetune时，finetune的细节配置与DINO原始论文一致，除了没有用1.5scale来训练。实验是在4卡v100上训练的。
（1）由于我这边算力的限制，1个epoch差不多8小时，我仅仅设置了12个epoch，然后在[8,11]个epoch分别把学习率变为原来的1/10。没有用denoising。
Epoch1: 55.2map
Epoch2: 55.5map
Epoch3: 55.7map
Epoch4: 46.3map  【很奇怪为啥会开始掉点】
Epoch5: 44.1map
（2）然后我改成在[4,8]个epoch把学习率变为原来的1/10，同样没有用denoising
Epoch1: 55.2map
Epoch2: 55.5map
Epoch3: 55.7map
Epoch4: 56.3map
Epoch5: 56.6map
Epoch6: 56.8map

我想知道为啥这里（1）处性能会突然变差。
finetune的时候需要denoising么
4卡，单卡bs为4时，性能会变差么
一般在哪几个epoch降低学习率

不胜感谢！！！

**Comment by Jordanyang** [comment]
你好，可以分享一下finutune代码参考一下吗

**Comment by merlinarer** [comment]
同求

**Comment by fangdaoyou** [comment]
我在尝试复现时也有这样的问题，我直接在开源权重上fine tune也达不到57，不过text encoder竟然是解冻的吗

**Comment by drilistbox** [comment]
> 

我是解冻的，你有什么建议么，我也不知道那种配置好。没有太多算力，1个epoch要8小时，等的头都大了。

**Comment by drilistbox** [comment]
> 我在尝试复现时也有这样的问题，我直接在开源权重上fine tune也达不到57，不过text encoder竟然是解冻的吗

我是解冻的，你有什么建议么，我也不知道那种配置好。没有太多算力，1个epoch要8小时，等的头都大了。

**Comment by fangdaoyou** [comment]
仔细想了一下，text encoder其实应该冻起来，毕竟如果它参与训练，回传的梯度会影响文本的表达

**Comment by Jordanyang** [comment]
GLIP模型的对齐loss看代码用的是dot_product_token_loss，但不太明白是怎么计算的(既预测和targets的token)，对应于GroundingDINO模型，不知如何对应，大佬可以解释一下吗

**Comment by dpxudong** [comment]
老哥们，我也在尝试复现他的训练部分你们方便留个联系方式一起交流一下吗？

**Comment by ccly1996** [comment]
求复现finetune代码

**Comment by wojiaohumaocheng** [comment]
求复现代码~

**Comment by wojiaohumaocheng** [comment]
> 老哥们，我也在尝试复现他的训练部分你们方便留个联系方式一起交流一下吗？

求复现代码

**Comment by Jordanyang** [comment]
> 
你好，匈牙利匹配过程中，contrastive losses是怎么实现的呢，我使用的是mdetr模块中的实现，
![image](https://github.com/IDEA-Research/GroundingDINO/assets/12427197/c8d69195-c88a-47a6-a9a2-2f3a7342e055)
,感觉这种方式计算的损失和最终GLIP loss使用的方式不一样

**Comment by Jordanyang** [comment]
作者你好，请问在匈牙利匹配过程中，contrastive losses(分类损失)是怎么实现的呢，有无参考

**Comment by Jordanyang** [comment]
> 
@drilistbox 你好，请问在匈牙利匹配过程中，contrastive losses(分类损失)是怎么实现的呢

**Comment by fangdaoyou** [comment]
> @drilistbox 你好，请问在匈牙利匹配过程中，contrastive losses(分类损失)是怎么实现的呢

可以参考MDETR

**Comment by Jordanyang** [comment]
好的 非常感谢，我参考mdetr，用contrastive losses作为匹配分数。

**Comment by Jordanyang** [comment]
> > @drilistbox 你好，请问在匈牙利匹配过程中，contrastive losses(分类损失)是怎么实现的呢
> 
> 可以参考MDETR

好的，非常感觉，我参考MDETR中的contrastive losses作为匈牙利算法中的匹配损失。

**Comment by Jordanyang** [comment]
> > @drilistbox 你好，请问在匈牙利匹配过程中，contrastive losses(分类损失)是怎么实现的呢
> 
> 可以参考MDETR

好的，非常感谢。

**Comment by Jordanyang** [comment]
> > @drilistbox 你好，请问在匈牙利匹配过程中，contrastive losses(分类损失)是怎么实现的呢
> 
> 可以参考MDETR

好的，非常感谢。

**Comment by Baboom-l** [comment]
其实直接拿DINO训也ok的

**Comment by shu-pi** [comment]
> ![image](https://user-images.githubusercontent.com/14495189/252830982-e070e6f0-3156-432a-8902-6ba37dbd1bcb.png) 作者您好，下面所有的描述都是以上图中红框的设置进行实验的。 我在复现groundingding的训练代码，用作者开源的swin-t在O365,GoldG,Cap4M上预训练模型，直接在coco val2017上评估，性能是48.4map。 然后在coco上的finetune时，finetune的细节配置与DINO原始论文一致，除了没有用1.5scale来训练。实验是在4卡v100上训练的。 （1）由于我这边算力的限制，1个epoch差不多8小时，我仅仅设置了12个epoch，然后在[8,11]个epoch分别把学习率变为原来的1/10。没有用denoising。 Epoch1: 55.2map Epoch2: 55.5map Epoch3: 55.7map Epoch4: 46.3map 【很奇怪为啥会开始掉点】 Epoch5: 44.1map （2）然后我改成在[4,8]个epoch把学习率变为原来的1/10，同样没有用denoising Epoch1: 55.2map Epoch2: 55.5map Epoch3: 55.7map Epoch4: 56.3map Epoch5: 56.6map Epoch6: 56.8map
> 
> 我想知道为啥这里（1）处性能会突然变差。 finetune的时候需要denoising么 4卡，单卡bs为4时，性能会变差么 一般在哪几个epoch降低学习率
> 
> 不胜感谢！！！

请问大佬可以分享一下训练部分的代码么~

**Comment by wangshuang-jiayou** [comment]
> 

麻烦问下你的GT是怎么做的呀？训练数据制作方式是参考DINO的嘛？还是有做其它改动呀

**Comment by xiaomoguhzz** [comment]
遇到了同样问题，在自己数据集finetune时第3轮性能会出现比较大的drop

**Comment by drilistbox** [comment]
把bert固定住 不finetune就好了

xiaomoguhzz ***@***.***> 于2023年9月11日周一 19:58写道：

**Comment by wangshuang-jiayou** [comment]
> 遇到了同样问题，在自己数据集finetune时第3轮性能会出现比较大的drop

可以请教一下，数据集制作是follow的哪篇论文嘛？

**Comment by ws1hope** [comment]
你好，我也在尝试训练grounding dino，想问一下3.5节提到的对比损失函数的标签是怎么构建的？

**Comment by wangshuang-jiayou** [comment]
> ![image](https://user-images.githubusercontent.com/14495189/252830982-e070e6f0-3156-432a-8902-6ba37dbd1bcb.png) 作者您好，下面所有的描述都是以上图中红框的设置进行实验的。 我在复现groundingding的训练代码，用作者开源的swin-t在O365,GoldG,Cap4M上预训练模型，直接在coco val2017上评估，性能是48.4map。 然后在coco上的finetune时，finetune的细节配置与DINO原始论文一致，除了没有用1.5scale来训练。实验是在4卡v100上训练的。 （1）由于我这边算力的限制，1个epoch差不多8小时，我仅仅设置了12个epoch，然后在[8,11]个epoch分别把学习率变为原来的1/10。没有用denoising。 Epoch1: 55.2map Epoch2: 55.5map Epoch3: 55.7map Epoch4: 46.3map 【很奇怪为啥会开始掉点】 Epoch5: 44.1map （2）然后我改成在[4,8]个epoch把学习率变为原来的1/10，同样没有用denoising Epoch1: 55.2map Epoch2: 55.5map Epoch3: 55.7map Epoch4: 56.3map Epoch5: 56.6map Epoch6: 56.8map
> 
> 我想知道为啥这里（1）处性能会突然变差。 finetune的时候需要denoising么 4卡，单卡bs为4时，性能会变差么 一般在哪几个epoch降低学习率
> 
> 不胜感谢！！！

我想请问一下，你有没有遇到这种情况，loss_label的地方，分类损失用sigmoid_focal_loss，loss为nan，查了下好像是因为预测的logits有-inf的值

**Comment by drilistbox** [comment]
> > ![image](https://user-images.githubusercontent.com/14495189/252830982-e070e6f0-3156-432a-8902-6ba37dbd1bcb.png) 作者您好，下面所有的描述都是以上图中红框的设置进行实验的。 我在复现groundingding的训练代码，用作者开源的swin-t在O365,GoldG,Cap4M上预训练模型，直接在coco val2017上评估，性能是48.4map。 然后在coco上的finetune时，finetune的细节配置与DINO原始论文一致，除了没有用1.5scale来训练。实验是在4卡v100上训练的。 （1）由于我这边算力的限制，1个epoch差不多8小时，我仅仅设置了12个epoch，然后在[8,11]个epoch分别把学习率变为原来的1/10。没有用denoising。 Epoch1: 55.2map Epoch2: 55.5map Epoch3: 55.7map Epoch4: 46.3map 【很奇怪为啥会开始掉点】 Epoch5: 44.1map （2）然后我改成在[4,8]个epoch把学习率变为原来的1/10，同样没有用denoising Epoch1: 55.2map Epoch2: 55.5map Epoch3: 55.7map Epoch4: 56.3map Epoch5: 56.6map Epoch6: 56.8map
> > 我想知道为啥这里（1）处性能会突然变差。 finetune的时候需要denoising么 4卡，单卡bs为4时，性能会变差么 一般在哪几个epoch降低学习率
> > 不胜感谢！！！
> 
> 我想请问一下，你有没有遇到这种情况，loss_label的地方，分类损失用sigmoid_focal_loss，loss为nan，查了下好像是因为预测的logits有-inf的值

你这里是label assign没有做好

**Comment by wangshuang-jiayou** [comment]
> > > ![image](https://user-images.githubusercontent.com/14495189/252830982-e070e6f0-3156-432a-8902-6ba37dbd1bcb.png) 作者您好，下面所有的描述都是以上图中红框的设置进行实验的。 我在复现groundingding的训练代码，用作者开源的swin-t在O365,GoldG,Cap4M上预训练模型，直接在coco val2017上评估，性能是48.4map。 然后在coco上的finetune时，finetune的细节配置与DINO原始论文一致，除了没有用1.5scale来训练。实验是在4卡v100上训练的。 （1）由于我这边算力的限制，1个epoch差不多8小时，我仅仅设置了12个epoch，然后在[8,11]个epoch分别把学习率变为原来的1/10。没有用denoising。 Epoch1: 55.2map Epoch2: 55.5map Epoch3: 55.7map Epoch4: 46.3map 【很奇怪为啥会开始掉点】 Epoch5: 44.1map （2）然后我改成在[4,8]个epoch把学习率变为原来的1/10，同样没有用denoising Epoch1: 55.2map Epoch2: 55.5map Epoch3: 55.7map Epoch4: 56.3map Epoch5: 56.6map Epoch6: 56.8map
> > > 我想知道为啥这里（1）处性能会突然变差。 finetune的时候需要denoising么 4卡，单卡bs为4时，性能会变差么 一般在哪几个epoch降低学习率
> > > 不胜感谢！！！
> > 
> > 
> > 我想请问一下，你有没有遇到这种情况，loss_label的地方，分类损失用sigmoid_focal_loss，loss为nan，查了下好像是因为预测的logits有-inf的值
> 
> 你这里是label assign没有做好

感谢！还想请教一下，匈牙利匹配过程中的cost class和 最终的label_loss分别follow的哪个方法或者论文复现的呐？

**Comment by drilistbox** [comment]
> > > > ![image](https://user-images.githubusercontent.com/14495189/252830982-e070e6f0-3156-432a-8902-6ba37dbd1bcb.png) 作者您好，下面所有的描述都是以上图中红框的设置进行实验的。 我在复现groundingding的训练代码，用作者开源的swin-t在O365,GoldG,Cap4M上预训练模型，直接在coco val2017上评估，性能是48.4map。 然后在coco上的finetune时，finetune的细节配置与DINO原始论文一致，除了没有用1.5scale来训练。实验是在4卡v100上训练的。 （1）由于我这边算力的限制，1个epoch差不多8小时，我仅仅设置了12个epoch，然后在[8,11]个epoch分别把学习率变为原来的1/10。没有用denoising。 Epoch1: 55.2map Epoch2: 55.5map Epoch3: 55.7map Epoch4: 46.3map 【很奇怪为啥会开始掉点】 Epoch5: 44.1map （2）然后我改成在[4,8]个epoch把学习率变为原来的1/10，同样没有用denoising Epoch1: 55.2map Epoch2: 55.5map Epoch3: 55.7map Epoch4: 56.3map Epoch5: 56.6map Epoch6: 56.8map
> > > > 我想知道为啥这里（1）处性能会突然变差。 finetune的时候需要denoising么 4卡，单卡bs为4时，性能会变差么 一般在哪几个epoch降低学习率
> > > > 不胜感谢！！！
> > > 
> > > 
> > > 我想请问一下，你有没有遇到这种情况，loss_label的地方，分类损失用sigmoid_focal_loss，loss为nan，查了下好像是因为预测的logits有-inf的值
> > 
> > 
> > 你这里是label assign没有做好
> 
> 感谢！还想请教一下，匈牙利匹配过程中的cost class和 最终的label_loss分别follow的哪个方法或者论文复现的呐？

glip

**Comment by wangshuang-jiayou** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/14495189/252830982-e070e6f0-3156-432a-8902-6ba37dbd1bcb.png) 作者您好，下面所有的描述都是以上图中红框的设置进行实验的。 我在复现groundingding的训练代码，用作者开源的swin-t在O365,GoldG,Cap4M上预训练模型，直接在coco val2017上评估，性能是48.4map。 然后在coco上的finetune时，finetune的细节配置与DINO原始论文一致，除了没有用1.5scale来训练。实验是在4卡v100上训练的。 （1）由于我这边算力的限制，1个epoch差不多8小时，我仅仅设置了12个epoch，然后在[8,11]个epoch分别把学习率变为原来的1/10。没有用denoising。 Epoch1: 55.2map Epoch2: 55.5map Epoch3: 55.7map Epoch4: 46.3map 【很奇怪为啥会开始掉点】 Epoch5: 44.1map （2）然后我改成在[4,8]个epoch把学习率变为原来的1/10，同样没有用denoising Epoch1: 55.2map Epoch2: 55.5map Epoch3: 55.7map Epoch4: 56.3map Epoch5: 56.6map Epoch6: 56.8map
> > > > > 我想知道为啥这里（1）处性能会突然变差。 finetune的时候需要denoising么 4卡，单卡bs为4时，性能会变差么 一般在哪几个epoch降低学习率
> > > > > 不胜感谢！！！
> > > > 
> > > > 
> > > > 我想请问一下，你有没有遇到这种情况，loss_label的地方，分类损失用sigmoid_focal_loss，loss为nan，查了下好像是因为预测的logits有-inf的值
> > > 
> > > 
> > > 你这里是label assign没有做好
> > 
> > 
> > 感谢！还想请教一下，匈牙利匹配过程中的cost class和 最终的label_loss分别follow的哪个方法或者论文复现的呐？
> 
> glip

想问下，你在finetune过程中，除了冻结了bert外，其它还冻结了什么嘛比如backbone。我遇到了一个问题，pretrain模型直接在coco eval上测试有48.5%的map，但是在自己的电力巡检数据集上finetune了以后，电力数据集能达到53%的map，但是得到的模型在原coco eval上测试只有3%的map了。我是只冻结了bert。不知道该怎么finetune了，想问下你有什么好的建议或经验嘛！不胜感激！！！

**Comment by LuciferZap** [comment]
> 我在尝试复现时也有这样的问题，我直接在开源权重上fine tune也达不到57，不过text encoder竟然是解冻的吗

可以加个联系方式吗?我的问题是数据集里面有些漏标,如果这样的数据送去训练在做loss的时候是否会影响模型的最终性能, 我看到GLIP里面会把负样本的类别加到训练里面, 但因为我的数据有漏标,可能会导致模型把部分没有标注的样本当成负样本去压制confidence
