### ISSUE TITLE
未知原因 "_C" 缺失报错

### ISSUE THREAD

**Issue by Everloom-129** [IDEA-Research/GroundingDINO#175]
前几天代码跑的好好的，今天突然反馈
NameError: name '_C' is not defined

整个代码找遍了没看到_C， 和GPT4诊断怀疑是库有问题，重新安装Pytorch+torchvision 两遍（2.00+0.15.0) 无法解决问题
求解答！
![image](https://github.com/IDEA-Research/GroundingDINO/assets/72364066/be0d6b7c-f761-496d-b27b-6ac5203d0fc4)

在新的服务器上从头开始配置，报了更奇怪的错误，不知道怎么解决（导入model时）
![image](https://github.com/IDEA-Research/GroundingDINO/assets/72364066/6e384734-341c-4058-9655-c9d4296a5c01)

**Comment by Everloom-129** [comment]
类似issue: https://blog.csdn.net/Cleo_Gao/article/details/130562873?spm=1001.2101.3001.6650.3&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7EYuanLiJiHua%7EPosition-3-130562873-blog-123622406.235%5Ev38%5Epc_relevant_sort_base3&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7EYuanLiJiHua%7EPosition-3-130562873-blog-123622406.235%5Ev38%5Epc_relevant_sort_base3&utm_relevant_index=4
但症结似乎不一样，我之前配置过没道理会坏的

**Comment by rentainhe** [comment]
> 前几天代码跑的好好的，今天突然反馈 NameError: name '_C' is not defined
> 
> 整个代码找遍了没看到_C， 和GPT4诊断怀疑是库有问题，重新安装Pytorch+torchvision 两遍（2.00+0.15.0) 无法解决问题 求解答！ ![image](https://user-images.githubusercontent.com/72364066/255236897-be0d6b7c-f761-496d-b27b-6ac5203d0fc4.png)
> 
> 在新的服务器上从头开始配置，报了更奇怪的错误，不知道怎么解决（导入model时） ![image](https://user-images.githubusercontent.com/72364066/255236465-6e384734-341c-4058-9655-c9d4296a5c01.png)

`_C`是setup.py中我们自定义的一个，用来保留GroundingDINO自定义的算子的库，这个需要你在安装GroundingDINO的时候设置一下CUDA_HOME, CUDA_HOME的路径要和你的CUDA Runtime一样例如

```bash
export CUDA_HOME=/path/to/cuda-11.3
```

如果你安装的是cuda-11.3环境的话

**Comment by rentainhe** [comment]
你可以对比一下你之前的环境下`CUDA_HOME`应该不是空的

**Comment by Everloom-129** [comment]
感谢！原来如此，我尝试一下

**Comment by Everloom-129** [comment]
> 你可以对比一下你之前的环境下`CUDA_HOME`应该不是空的
我在RTX3090 LINUX server上跑，CUDA 版本是11.3
之前没有设置cuda_home,所以代码应该是在cpu模式下跑的，因此没有相关信息
但是现在重新配置发现c++混合边缘代码处问题， 我正在尝试重新在另外一台相同配置的服务器上重新走一遍流程

**Comment by Everloom-129** [comment]
figure out! 就是没安装cuda 导致的
我可以给groundingDINO readme installation part 增加一些东西吗？我稍后发起一个request, 感谢作者团队

**Comment by yangchengxin** [comment]
兄弟，我是windows系统，已经安装了cuda，cuda版本torch，cuda版本torchvision，并且cuda_home也指定好了  为啥还是报错呀

**Comment by Everloom-129** [comment]
你现在还有报错吗？这个_C多半是依赖库的问题
我是linux, win10版本大多不稳定，你可以翻翻之前的issue history

**Comment by yangchengxin** [comment]
有报错的，我就是按照这个流程下来的，但是环境一直有问题，就是正常不了这个_c，我用的是windows11系统，所以我怀疑有可能是系统问题，最近没有在搞了



---- 回复的原邮件 ----
| 发件人 | Tony ***@***.***> |
| 日期 | 2023年08月07日 16:38 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [IDEA-Research/GroundingDINO] 未知原因 "_C" 缺失报错 (Issue #175) |

你现在还有报错吗？这个_C多半是依赖库的问题
我是linux, win10版本大多不稳定，你可以翻翻之前的issue history

**Comment by AzulYang** [comment]
> 你可以对比一下你之前的环境下`CUDA_HOME`应该不是空的

你好，我的代码使用了GROUNDINGDINO，我在cpu上可以运行，但是切换到cuda就会出现这个错误，由于我已经安装完成GROUNDINGDINO，我不太清楚这个应该在哪里添加，可以给一点建议吗

**Comment by Everloom-129** [comment]
> > 你可以对比一下你之前的环境下`CUDA_HOME`应该不是空的
> 
> 你好，我的代码使用了GROUNDINGDINO，我在cpu上可以运行，但是切换到cuda就会出现这个错误，由于我已经安装完成GROUNDINGDINO，我不太清楚这个应该在哪里添加，可以给一点建议吗

你可以参考最新的readme, 这个环境变量是linux系统下的，需要保存到.bashrc 文件里才能在新的terminal 里使用cuda
