### ISSUE TITLE
ERROR: No matching distribution found for supervision==0.4.0

### ISSUE THREAD

**Issue by wavelet2008** [IDEA-Research/GroundingDINO#19]
pip install supervision==0.4.0 -f https://download.pytorch.org/whl/torch_stable.html  -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
Looking in indexes: http://pypi.douban.com/simple
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement supervision==0.4.0 (from versions: 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.3.1)
ERROR: No matching distribution found for supervision==0.4.0

**Comment by SlongLiu** [comment]
it seems like you constraint the pypi source. 
Can you try: `pip install supervision==0.4.0` directly? Or use another version as instructions like 0.3.1

**Comment by SkalskiP** [comment]
Yeah, `supervision==0.4.0` is accessible in [PyPI](https://pypi.org/project/supervision/). Plain `pip install supervision==0.4.0` should work.

**Comment by wavelet2008** [comment]
thanks  @SkalskiP  @SlongLiu   ,try  supervision  source  install

**Comment by Mingkimon** [comment]
Hi all, I run `pip3 install supervision==0.4.0` (and i've also tried pip) directly, but still cannot fix this problem:
