### ISSUE TITLE
Can't download pre-training model

### ISSUE THREAD

**Issue by gufra-lee** [IDEA-Research/GroundingDINO#205]
I don't know if it's because the model is too big or I can't find this pre-trained model. I can't download it by running the wget command.

**Comment by rentainhe** [comment]
> I don't know if it's because the model is too big or I can't find this pre-trained model. I can't download it by running the wget command.

Which pretrained weights do you need, you can download them from:
- Grounding-DINO pretarined weights from `Github`
- BERT from `Huggingface`

**Comment by rentainhe** [comment]
Our github released models: https://github.com/IDEA-Research/GroundingDINO/releases

**Comment by gufra-lee** [comment]
thanks

**Comment by rentainhe** [comment]
You're welcome

**Comment by rentainhe** [comment]
I'm closing this issue, feel free to reopen it if needed or report a new issue
