### ISSUE TITLE
Difference between GroundingDINO and UniDetector.

### ISSUE THREAD

**Issue by synsin0** [IDEA-Research/GroundingDINO#25]
I am a fresh hand for open-set OD. Now I try to learn the difference between your Grounding DINO with UniDetector. Both can implement open-set detection. I think the difference may be, for each dataset, you need to prompt the novel labels into the network for zero-shot, but the UniDetector inputs many prompts, not limited to the labels in each dataset. Besides, may you provide more insight on the contributions of GroundingDINO? The answer will be helpful to me. Thanks!

**Comment by SlongLiu** [comment]
You can view our paper for more details. Our model supports any text inputs, which means you can detect everything you can think of. Moreover, we use grounded pre-training, which enables to detect the noun phrases in input sentences. It cannot be finished in the UniDetector.

**Comment by synsin0** [comment]
I understand GroundingDINO's ability of grounding in the context and especially in REC tasks. Thanks for your great work and timely response.
