### ISSUE TITLE
onnx with dynamic input sizes

### ISSUE THREAD

**Issue by goldentimejsky** [IDEA-Research/GroundingDINO#258]
Hi @wenyi5608 Thanks for your great effort for converting grounding dino to onnx. I have converted the model to onnx, but there is a bug when modifying the size of input images. I have changed the operation `reshape` to `view` in the swin backbone, but the bug still exists. Can you input images with different sizes? Do you have suggestions on this bug? Thank you in advance.

![屏幕截图 2023-12-04 181045](https://github.com/IDEA-Research/GroundingDINO/assets/42629269/15526c43-485c-4f80-b3e6-cda4a106f5eb)

**Comment by wenyi5608** [comment]
hi, @goldentimejsky  Torch.onnx.export exports the structure diagram of the model based on the input image size. The onnx model structure diagram exported with different input sizes will be different. Although the exported onnx model is dynamic, if the input image size is inconsistent with the image size you use to convert the model, the model may be unable to inference.

**Comment by goldentimejsky** [comment]
> hi, @goldentimejsky Torch.onnx.export exports the structure diagram of the model based on the input image size. The onnx model structure diagram exported with different input sizes will be different. Although the exported onnx model is dynamic, if the input image size is inconsistent with the image size you use to convert the model, the model may be unable to inference.

Hi, @wenyi5608 Thanks for your reply. I found that onnx model could support dynamic input scales if it is exported with `dynamic_axes`, (e.g. [the blog](https://blog.csdn.net/weixin_38443388/article/details/108677003)) I tried to input with different text length and it was ok. But inputs with different scales always fail. Does that mean the model exported with `dynamic_axes` just support dynamic text length but not dynamic image scales?

**Comment by wenyi5608** [comment]
Different input image scales have different inference branches. When you export onnx model, you can look at the warning information to see which layers are related to the image scale.

**Comment by goldentimejsky** [comment]
Thanks @wenyi5608 for answering the question. I understand it.

**Comment by goldentimejsky** [comment]
Hi @wenyi5608 another time to bother you.
When I inference with onnx, the avarage time is more than 2s per image. But the ckpt inference time is less than 1s per image.
If I specify the `providers` as `'CUDAExecutionProvider'`, a warning 

`2023-12-05 15:22:07.752144757 [W:onnxruntime:, session_state.cc:1162 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-12-05 15:22:07.752177577 [W:onnxruntime:, session_state.cc:1164 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.`

may denote that onnx runs on CPU instead of GPU because of some operations.

When I specify the `providers` as `'CUDAExecutionProvider'` and `'CPUExecutionProvider'`, the warning disappears but the inference speed is still slow. Have you met this problem?

**Comment by wenyi5608** [comment]
Hi @goldentimejsky Sorry, I didn't test CUDAExecutionProvider.

**Comment by goldentimejsky** [comment]
> Hi @goldentimejsky Sorry, I didn't test CUDAExecutionProvider.

Fine. Thanks again for your effort and help.

**Comment by blacksino** [comment]
Have you solved this problem?
I have convert dino to onnx and inference speed is quite slow as you have met.

**Comment by skydh** [comment]
> 您解决了这个问题吗？ 我已将 dino 转换为 onnx，但推理速度却像您遇到的那样非常慢。

大佬，解决了吗，求解决方案

**Comment by skydh** [comment]
> > 你好@goldentimejsky抱歉，我没有测试 CUDAExecutionProvider。
> 
> 很好。再次感谢您的努力和帮助。

大佬，如何解决的
