### ISSUE TITLE
How many epochs did you train on O365 datasets?

### ISSUE THREAD

**Issue by mayoycy** [IDEA-Research/GroundingDINO#5]
Hello! I'd like to know how many epochs did you train GroundingDINO (with Swin-Tiny and Swin-Large) on O365 datasets?

**Comment by SlongLiu** [comment]
We train the models until it convergences. 
The approximate time is about 50 epochs.

**Comment by mayoycy** [comment]
> We train the models until it convergences. The approximate time is about 50 epochs.

Thanks for your reply.
Best Regards.
