### ISSUE TITLE
How to improve inference speed?

### ISSUE THREAD

**Issue by JiajieZhuang** [IDEA-Research/GroundingDINO#50]
Hello, I want to know if there is a way to improve model's inference speed. It takes about 1.5 seconds for my machine (i9-11900KF+RTX 3080 Ti) to perform one inference, while in Appendix.I of the paper, the FPS can reach 8.37. I would like to ask how you achieved this? What was the configuration during testing?

Thanks !

**Comment by checksummaster** [comment]
My first frame takes 2.2 sec (first call to predict), but others are faster, like 0.4 sec (5x faster). (RTX2080).

**Comment by JiajieZhuang** [comment]
> My first frame takes 2.2 sec (first call to predict), but others are faster, like 0.4 sec (5x faster). (RTX2080).
Oh thank you! Indeed, the processing speed of subsequent frames can be greatly improved. An FPS of 8.37 appears to be a reasonable results, and the issue has been resolved.

**Comment by aisagarw** [comment]
Hi!
I am also facing issues with the inference speed. Did you have to modify anything in the inference code?

**Comment by ultimate-w4** [comment]
Hello there, i'm getting 9s per recognition, my config:


MODEL_ID = "IDEA-Research/grounding-dino-tiny"
device = "cuda" if torch.cuda.is_available() else "cpu"
processor = AutoProcessor.from_pretrained(MODEL_ID)
model = AutoModelForZeroShotObjectDetection.from_pretrained(MODEL_ID).to(device)
model.eval()

    inputs = processor(images=image, text=classes, return_tensors="pt").to(device)

    t_image = time.time() - t0

    with torch.no_grad():
        outputs = model(**inputs)

    results = processor.post_process_grounded_object_detection(
        outputs,
        inputs.input_ids,
        box_threshold=0.4,
        text_threshold=0.4,
        target_sizes=[image.size[::-1]],  # (H, W)
    )
    res = results[0]

elapsed = time.time() - t0
return {
    "success": True,
    "t_image": t_image,
    "time": elapsed,
    "rows": rows,
    "cols": cols,
    "indices": sorted(list(indices_set)),  # ej: [2,5,8]
    "per_cell": per_cell                   # detalle por celda (opcional)
}

What's wrong with my code

<img width="478" height="179" alt="Image" src="https://github.com/user-attachments/assets/f1c976f9-1d71-4843-9507-fc0d6a81830b" />

<img width="561" height="554" alt="Image" src="https://github.com/user-attachments/assets/aa53c001-4c0f-40cf-8cc6-e8ec200c637d" />
