### ISSUE TITLE
Reverse engineer prompt

### ISSUE THREAD

**Issue by tall-josh** [IDEA-Research/GroundingDINO#55]
Hi

Firstly thanks for the awesome work, very cool!

I was wondering if it's possible to reverse engineer a prompt given a bounding box?

**Comment by SlongLiu** [comment]
wow it is an interesting idea. our model doesn't support yet. but it may be an interesting work to explore

**Comment by tall-josh** [comment]
Thanks, no doubt a model will drop in a week or 2 that can do it :-p 
I think it would be useful for the case where a user it trying to detect something that's hard to describe. At the moment it sometimes feels like one of those old text-based games where you have to guess the exact command to make the player move through the game. 

Anyway, have a good day, thanks for your work!
