### ISSUE TITLE
Possible to avoid merging categories?

### ISSUE THREAD

**Issue by segments-tobias** [IDEA-Research/GroundingDINO#63]
For [zero-shot panoptic segmentation with SAM](https://github.com/segments-ai/panoptic-segment-anything), I'm inputting classes separated by " . "

However, when the class names are semantically similar, they often get merged (e.g. "car . taxi ." become "car taxi" in the phrases). Is there any way this can be avoided? @SlongLiu

**Comment by confusedgreenhand** [comment]
In addition to tag merging, there will also be tag error problems, such as the correct label is ‘tricycle’, but the output label is ‘tri’; or  'van' becomes '##van'. 
![merge and wrong](https://user-images.githubusercontent.com/49227338/233290215-3d92968e-580f-4a57-8551-627535753860.png)

**Comment by egeozguroglu** [comment]
@SlongLiu Thanks for the amazing work. I've been encountering the same tag merging issue. Any insight would be appreciated.

**Comment by ManiaaJia** [comment]
The same problem.

**Comment by cyty98** [comment]
The same problem.

**Comment by kqdlx3** [comment]
the same problem

**Comment by Rivoks** [comment]
For those having this problem, this solution works well for me:
```python
from groundingdino.util.inference import predict

boxes, scores, pred_classes = predict(
            model=model,
            image=image_tsr,
            caption=TEXT_PROMPT,
            box_threshold=BOX_THRESHOLD,
            text_threshold=TEXT_THRESHOLD,
            remove_combined=True # <== This will remove the combined phrases outputs
        )
```

**Comment by segments-tobias** [comment]
Closed by [https://github.com/IDEA-Research/GroundingDINO/pull/125](https://github.com/IDEA-Research/GroundingDINO/pull/125)
