### ISSUE TITLE
how to get cuda path when ubuntu wsl2?

### ISSUE THREAD

**Issue by mattdst1** [IDEA-Research/GroundingDINO#64]
Looking into this on my wsl2 ubuntu setup. How should I handle the cuda path when working in windows subsystem for linux 2?

```
>> os.environ.get("CUDA_PATH")
'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7'
```

but in wsl2:
```
>> os.environ.get("CUDA_PATH")'

None
```

**Comment by Macleodsolutions** [comment]
Working in Win11 with WSL2 Ubuntu 20.04:
-Newest geforce drivers installed in windows, no driver installed in WSL2. (At this point, nvidia-smi should work in ubuntu but nvcc won't.)
-Install pytorch for cuda 11.7: `conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia`
-Install the runfile for the matching cuda toolkit in ubuntu: https://developer.nvidia.com/cuda-11-7-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=runfile_local

Done! (hopefully)
