### ISSUE TITLE
NameError: name '_C' is not defined

### ISSUE THREAD

**Issue by HassanBinHaroon** [IDEA-Research/GroundingDINO#80]
51     ):
     52         ctx.im2col_step = im2col_step
---> 53         output = _C.ms_deform_attn_forward(
     54             value,
     55             value_spatial_shapes,

NameError: name '_C' is not defined

**Comment by HassanBinHaroon** [comment]
[Solved]

First I was doing installation using "pip install -r requirements.txt". It didn't work.

Finally I installed using this command and it worked "pip install -q -e ."

I was running on Colab

**Comment by congzhou09** [comment]
Same NameError in colab, and I solved this by following two steps:
1. Copy [the README shared notebook](https://colab.research.google.com/drive/1P3jJqKEWEaeNcZg8fODbbWeQ3gxOHk2-?usp=sharing) into your own colab space.
2. After the pip installation, a "restart the runtime" button will be showed in the output, click that button.

**Comment by bloodhunt3r** [comment]
simply install the groundingDINO with this command:
```shell
cd groundingDINO
pip install .
```
this will build the wheel with C++ extensions and install the whole wheel to your environment.
