### ISSUE TITLE
New API has a bug in processing list of prompts

### ISSUE THREAD

**Issue by darshats** [IDEA-Research/GroundingDINO#86]
The recommended way to look for multiple objects is separated by "." 
In the new API, it takes a List of prompts and but then concatenates them as comma separated instead of dot separated. This actually makes a difference to the output of inference call.

I can raise a PR but its a simple fix in prompt processing on line 192 of inference.py

Thanks!

**Comment by rentainhe** [comment]
Thanks for fixing this issue, we've already merged your PR, welcome to be new contributors of GroundingDINO!
